
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Thu May 05 14:05:40 VET 2016
//----------------------------------------------------

package Tiny;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int TIMES = 19;
  public static final int AND = 25;
  public static final int READ = 10;
  public static final int OVER = 20;
  public static final int LT = 16;
  public static final int ELSE = 4;
  public static final int PLUS = 17;
  public static final int LQ = 27;
  public static final int OR = 26;
  public static final int RPAREN = 22;
  public static final int THEN = 3;
  public static final int SEMI = 23;
  public static final int WHILE = 7;
  public static final int END = 5;
  public static final int IF = 2;
  public static final int GT = 28;
  public static final int LPAREN = 21;
  public static final int WRITE = 11;
  public static final int ID = 12;
  public static final int GQ = 29;
  public static final int NUM = 13;
  public static final int BEGIN = 24;
  public static final int DO = 8;
  public static final int EOF = 0;
  public static final int MINUS = 18;
  public static final int error = 1;
  public static final int UNTIL = 9;
  public static final int ASSIGN = 14;
  public static final int EQ = 15;
  public static final int NQ = 30;
  public static final int FOR = 31;
  public static final int REPEAT = 6;
}

